= GCO BSP

To get the BSP you need to have `repo` installed and use it as:

Install the `repo` utility:

[source,console]
$: mkdir ~/bin
$: curl http://commondatastorage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
$: chmod a+x ~/bin/repo

Download the BSP source:

[source,console]
$: PATH=${PATH}:~/bin
$: mkdir gco-bsp
$: cd gco-bsp
$: repo init -u https://github.com/jfpastrana/v2x-platform-test.git -b sumo
$: repo sync

At the end of the commands you have every metadata you need to start work with.

To start a simple image build:

[source,console]
$: source MACHINE=solidrun-imx6 DISTRO=poky source setup-environment build
$: bitbake core-image-v2x-dev

You can use any directory to host your build.

The source code is checked out at `sources`.

== Contributing

To contribute to this layer you should send the patches for review to the mailing list.

Mailing list::
    https://lists.yoctoproject.org/listinfo/meta-freescale

Source code::
    https://github.com/Freescale/fsl-community-bsp-platform

When creating patches, please use something like:

[source,console]
$: git format-patch -s --subject-prefix='gco-v2x-bsp-platform][PATCH][sumo' origin

When sending patches, please use something like:

[source,console]
$: git send-email --to javier.fernandez.pastrana@gmail.com <generated patch>

== Using Development and Testing Branches

Replace the `repo init` command above with one of the following:

master:: For developers
+
[source,console]
$: repo init -u https://github.com/jfpastrana/v2x-platform-test -b sumo
